---
apiVersion: v1
kind: ConfigMap
metadata:
  name: coralogix-demo-akhq
  namespace: OVERLOADED_DURING_KUSTOMIZATION
data:
  AKHQ_CONFIGS_GLOBAL_BOOTSTRAP_SERVERS: "OVERLOADED_DURING_KUSTOMIZATION"
  AKHQ_CONFIGURATION: "OVERLOADED_DURING_KUSTOMIZATION"
---  
apiVersion: apps/v1
kind: Deployment
metadata:
  name: coralogix-demo-akhq
  namespace: OVERLOADED_DURING_KUSTOMIZATION
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coralogix-demo-akhq
  template:
    metadata:
      labels:
        app: coralogix-demo-akhq
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: type
                operator: In
                values:
                - message-queue
      containers:
        - name: OVERLOADED_DURING_KUSTOMIZATION
          image: OVERLOADED_DURING_KUSTOMIZATION
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 100m # 1 CPU core = 1000m
              memory: 256Mi # 256 megabytes, 512 megabytes, 768 megabytes, 1024 megabytes
            requests:
              cpu: 50m  # 0.75 CPU cores = 750m
              memory: 64Mi  # 256 megabytes, 512 megabytes, 768 megabytes, 1024 megabytes
          envFrom:
            - configMapRef:
                name: coralogix-demo-akhq
---
apiVersion: v1
kind: Service
metadata:
  name: coralogix-demo-akhq
  namespace: OVERLOADED_DURING_KUSTOMIZATION
spec:
  selector:
    app: coralogix-demo-akhq
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP  
---
apiVersion: v1
kind: Service
metadata:
  name: coralogix-demo-akhq-external
  namespace: OVERLOADED_DURING_KUSTOMIZATION
spec:
  selector:
    app: coralogix-demo-akhq
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer  