apiVersion: v1
kind: ConfigMap
metadata:
  name: coralogix-demo-create-order-audit
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: coralogix-demo-create-order-audit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coralogix-demo-create-order-audit
  template:
    metadata:
      labels:
        app: coralogix-demo-create-order-audit
    spec:
      containers:
        - name: OVERLOADED_DURING_KUSTOMIZATION
          ports:
            - containerPort: 8089
          env:
            - name: SPRING_DATA_MONGODB_URI
              valueFrom:
                configMapKeyRef:
                  name: coralogix-demo-create-order-audit
                  key: SPRING_DATA_MONGODB_URI
            - name: SPRING_DATA_MONGODB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: coralogix-demo-create-order-audit
                  key: SPRING_DATA_MONGODB_DATABASE
            - name: KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: coralogix-demo-create-order-audit
                  key: KAFKA_BOOTSTRAP_SERVERS
---
apiVersion: v1
kind: Service
metadata:
  name: coralogix-demo-create-order-audit
spec:
  selector:
    app: coralogix-demo-create-order-audit
  ports:
    - protocol: TCP
      port: 8089
      targetPort: 8089
  type: ClusterIP
