---
apiVersion: v1
kind: ConfigMap
metadata:
  name: coralogix-demo-akhq
---  
apiVersion: apps/v1
kind: Deployment
metadata:
  name: coralogix-demo-akhq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coralogix-demo-akhq
  template:
    metadata:
      labels:
        app: coralogix-demo-akhq
    spec:
      containers:
        - name: OVERLOADED_DURING_KUSTOMIZATION
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: coralogix-demo-akhq
---
apiVersion: v1
kind: Service
metadata:
  name: coralogix-demo-akhq
spec:
  selector:
    app: coralogix-demo-akhq
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
---
#apiVersion: v1
#kind: Service
#metadata:
#  name: coralogix-demo-akhq-external
#spec:
#  selector:
#    app: coralogix-demo-akhq
#  ports:
#    - protocol: TCP
#      port: 8080
#      targetPort: 8080
#  type: LoadBalancer