---
apiVersion: v1
kind: ConfigMap
metadata:
  name: coralogix-demo-zookeeper
  namespace: OVERLOADED_DURING_KUSTOMIZATION
data:
  ZOOKEEPER_CLIENT_PORT: "OVERLOADED_DURING_KUSTOMIZATION"
  ZOOKEEPER_TICK_TIME: "OVERLOADED_DURING_KUSTOMIZATION"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: coralogix-demo-zookeeper
  namespace: OVERLOADED_DURING_KUSTOMIZATION
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coralogix-demo-zookeeper
  template:
    metadata:
      labels:
        app: coralogix-demo-zookeeper
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: type
                operator: In
                values:
                - message-queue
      containers:
        - name: OVERLOADED_DURING_KUSTOMIZATION
          image: OVERLOADED_DURING_KUSTOMIZATION
          ports:
            - containerPort: 2181
          resources:
            limits:
              cpu: 250m # 1 CPU core = 1000m
              memory: 512Mi # 256 megabytes, 512 megabytes, 768 megabytes, 1024 megabytes
            requests:
              cpu: 100m  # 0.75 CPU cores = 750m
              memory: 64Mi  # 256 megabytes, 512 megabytes, 768 megabytes, 1024 megabytes
          envFrom:
            - configMapRef:
                name: coralogix-demo-zookeeper
---
apiVersion: v1
kind: Service
metadata:
  name: coralogix-demo-zookeeper
  namespace: OVERLOADED_DURING_KUSTOMIZATION
spec:
  selector:
    app: coralogix-demo-zookeeper
  ports:
    - protocol: TCP
      port: 2181
      targetPort: 2181
  type: ClusterIP  