---
apiVersion: v1
kind: ConfigMap
metadata:
  name: coralogix-demo-kafka
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: coralogix-demo-kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coralogix-demo-kafka
  template:
    metadata:
      labels:
        app: coralogix-demo-kafka
    spec:
      containers:
        - name: OVERLOADED_DURING_KUSTOMIZATION
          ports:
            - containerPort: 9092
          envFrom:
            - configMapRef:
                name: coralogix-demo-kafka
---
apiVersion: v1
kind: Service
metadata:
  name: coralogix-demo-kafka
spec:
  selector:
    app: coralogix-demo-kafka
  ports:
    - protocol: TCP
      port: 9092
      targetPort: 9092
  type: ClusterIP  